NORMALIZATION PROBLEM

In [2]:
import numpy as np

In [3]:
X = np.random.rand(5,5) #Creating random 5x5 ndarray

#Compute mean and standard dev
mean = X.mean() 
std = X.std()

#Normalize Formula
X_normalized = (X - mean) / std

#File to save
np.save("X_normalized .npy", X_normalized)

#Not needed but just to show the data and results
print("Original X:\n", X)
print("\nNormalized X:\n", X_normalized)

Original X:
 [[0.42030315 0.40046118 0.93681447 0.20570728 0.13405735]
 [0.68117391 0.73909913 0.44345038 0.42459215 0.01624564]
 [0.55781798 0.99784568 0.54429756 0.27185666 0.60960441]
 [0.87547755 0.9195077  0.64047702 0.31495671 0.16358445]
 [0.41824112 0.25076977 0.77815131 0.38147443 0.82998255]]

Normalized X:
 [[-0.36271049 -0.43619703  1.55023589 -1.15748572 -1.42284771]
 [ 0.60344795  0.81797925 -0.27698266 -0.3468258  -1.85917406]
 [ 0.14658812  1.77627048  0.09651399 -0.9124955   0.33838382]
 [ 1.32306907  1.48613868  0.45272333 -0.75287057 -1.31349146]
 [-0.37034742 -0.9905927   0.96261253 -0.5065162   1.1545742 ]]


DIVISIBLE BY 3 PROBLEM

In [6]:

A = np.arange(1,101) ** 2 #creates a sequence, then squaring it after
A = A.reshape(10,10) #reshaping to 10x10 (rows and columns)

div_by_3= A[A % 3 ==0] # Using the elements that are divisble by 3 (Specifically boolean type)

np.save("div_by_3.npy",div_by_3) # Saving the results to a file

#Not needed but just to show the data and results
print("\n",A)
print("Divisible by 3", div_by_3)


 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
Divisible by 3 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
